
package ui;

import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoctorDirectory;
import model.Hospital;
import model.HospitalDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Shashank
 */
public class CommunityAdminPage extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdminPage
     */
    
    Hospital hospital;
    Person person;
    HospitalDirectory directory;
    PersonDirectory personDirectory;
    
    // default constructor
    public CommunityAdminPage() {             
    }
    
    // parameterized constructor
    public CommunityAdminPage(HospitalDirectory directory, PersonDirectory personDirectory) {
        initComponents();
        this.directory = directory;
        this.personDirectory = personDirectory;
        
        this.setTitle("HOSPITAL MANAGEMENT SYSTEM");   // sets title of the this
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   //exit out of application
        this.setSize(1300, 680);   //sets x and y dimeensions of this
        this.getContentPane().setBackground(Color.darkGray);   //change color of background
        this.setVisible(true); // makes this visible
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblCommunityAdminPage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHospitalHeader = new javax.swing.JLabel();
        lblHouseHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHouseDetails = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHospitalDetails = new javax.swing.JTable();
        btnClear1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();
        lblHospitalName = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        lblHospitalAddress = new javax.swing.JLabel();
        txtHospitalAddress = new javax.swing.JTextField();
        lblHospitalCity = new javax.swing.JLabel();
        txtHospitalCity = new javax.swing.JTextField();
        lblHospitalZipCode = new javax.swing.JLabel();
        txtHospitalZipCode = new javax.swing.JTextField();
        lblHouseName = new javax.swing.JLabel();
        txtHouseName = new javax.swing.JTextField();
        lblHouseAddress = new javax.swing.JLabel();
        txtHouseAddress = new javax.swing.JTextField();
        lblHouseCity = new javax.swing.JLabel();
        txtHouseCity = new javax.swing.JTextField();
        lblHouseZipCode = new javax.swing.JLabel();
        txtHouseZipCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnHome.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnHome.setText("Home");
        BtnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        btnHospital.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnHospital.setText("Hospital ");
        btnHospital.setMaximumSize(new java.awt.Dimension(49, 26));
        btnHospital.setMinimumSize(new java.awt.Dimension(49, 26));
        btnHospital.setPreferredSize(new java.awt.Dimension(49, 26));
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });

        btnDoctor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setMaximumSize(new java.awt.Dimension(49, 26));
        btnDoctor.setMinimumSize(new java.awt.Dimension(49, 26));
        btnDoctor.setPreferredSize(new java.awt.Dimension(49, 26));
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(btnHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(BtnHome)
                .addGap(47, 47, 47)
                .addComponent(btnHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        lblCommunityAdminPage.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblCommunityAdminPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunityAdminPage.setText("COMMUNITY ADMIN PAGE");

        lblHospitalHeader.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalHeader.setText("Hospital Details");

        lblHouseHeader.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHouseHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseHeader.setText("House Details");

        tblHouseDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblHouseDetails.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblHouseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "City", "Zip Code", "Phone", "Email"
            }
        ));
        tblHouseDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHouseDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHouseDetails);

        btnUpdate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblHospitalDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblHospitalDetails.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblHospitalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "City", "Zip Code", "Phone", "Email"
            }
        ));
        tblHospitalDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHospitalDetails);

        btnClear1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClear1.setText("Clear");
        btnClear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnUpdate1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseClicked(evt);
            }
        });
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnView1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnView1.setText("View");
        btnView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnView1MouseClicked(evt);
            }
        });
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });

        lblHospitalName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalName.setText("Hospital Name");
        lblHospitalName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalAddress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalAddress.setText("Address");
        lblHospitalAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalCity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalCity.setText("City");
        lblHospitalCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalZipCode.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalZipCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalZipCode.setText("Zip Code");
        lblHospitalZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHouseName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHouseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseName.setText("House Name");
        lblHouseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHouseAddress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHouseAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseAddress.setText("Address");
        lblHouseAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHouseCity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHouseCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseCity.setText("City");
        lblHouseCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHouseZipCode.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHouseZipCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHouseZipCode.setText("Zip Code");
        lblHouseZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCommunityAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jSeparator1)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHospitalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouseHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHospitalAddress))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHospitalName, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHospitalCity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHospitalZipCode)))
                                .addGap(53, 53, 53))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHouseZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHouseZipCode))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHouseCity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHouseCity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHouseAddress))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtHouseName)))
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCommunityAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalHeader)
                    .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(btnUpdate)))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHouseHeader))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear1)
                            .addComponent(btnUpdate1)
                            .addComponent(btnView1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(535, Short.MAX_VALUE)))
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout splitPaneLayout = new javax.swing.GroupLayout(splitPane);
        splitPane.setLayout(splitPaneLayout);
        splitPaneLayout.setHorizontalGroup(
            splitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        splitPaneLayout.setVerticalGroup(
            splitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // VIEW button code here:
        //populateDetails(tblHouseDetails);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // CANCEL or CLEAR button code here:
        // call function to clear input fields
        //clearfields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // UPDATE functionality code here:
        // once data is set on textfield apply update operation
//        int selectedRowIndex = tblHouseDetails.getSelectedRow();
//        if (selectedRowIndex < 0) {
//            JOptionPane.showMessageDialog(this, "Please select a row to update");
//            return;
//        }
//
//        // Get table model
//        DefaultTableModel tblModel = (DefaultTableModel) tblHouseDetails.getModel();
//        Hospital selectedHospital = (Hospital) tblModel.getValueAt(selectedRowIndex, 0);
//        // set data from text field to the selected hospital respective place
//        selectedHospital.setHospitalName(txtHospitalName.getText());
//        selectedHospital.setAddress(txtHospitalAddress.getText());
//        selectedHospital.setCity(txtHospitalCity.getText());
//        selectedHospital.setZipCode(txtHospitalZipCode.getText());
//        selectedHospital.setPhone(txtHospitalPhone.getText());
//        selectedHospital.setEmail(txtHospitalEmail.getText());

//        tblModel.setValueAt(selectedHospital.getHospitalName(), selectedRowIndex, 0);
//        tblModel.setValueAt(selectedHospital.getAddress(), selectedRowIndex, 1);
//        tblModel.setValueAt(selectedHospital.getCity(), selectedRowIndex, 2);
//        tblModel.setValueAt(selectedHospital.getZipCode(), selectedRowIndex, 3);
//        tblModel.setValueAt(selectedHospital.getPhone(), selectedRowIndex, 4);
//        tblModel.setValueAt(selectedHospital.getEmail(), selectedRowIndex, 5);

        //JOptionPane.showMessageDialog(this, "Hospital details updated successfully in the hospital directory");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // UPDATE mouse click event code here:
        // when row is selected, data will set tinto textfield for update
        //        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
        //
        //        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
        //        //
        //        txtHospitalName.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
        //        txtHospitalAddress.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
        //        txtHospitalCity.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
        //        txtHospitalZipCode.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
        //        txtHospitalPhone.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
        //        txtHospitalEmail.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tblHouseDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHouseDetailsMouseClicked
        // Hospital details table mouse click event code here:
        // when row is selected, data will set to textfield for update
        //populateDetails(tblHospitalDetails);

        //        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
        //        // invoke the table model
        //        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
        //        // get value from respective fields and set it to String Attributes
        //
        //        txtHospitalName.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
        //        txtHospitalAddress.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
        //        txtHospitalCity.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
        //        txtHospitalZipCode.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
        //        txtHospitalPhone.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
        //        txtHospitalEmail.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_tblHouseDetailsMouseClicked

    private void tblHospitalDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHospitalDetailsMouseClicked

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseClicked

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnView1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnView1MouseClicked

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnView1ActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // HOME button action performed code here:
        MainJFrame obj = new MainJFrame();
        obj.setVisible(true);
        //dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnView1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCommunityAdminPage;
    private javax.swing.JLabel lblHospitalAddress;
    private javax.swing.JLabel lblHospitalCity;
    private javax.swing.JLabel lblHospitalHeader;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalZipCode;
    private javax.swing.JLabel lblHouseAddress;
    private javax.swing.JLabel lblHouseCity;
    private javax.swing.JLabel lblHouseHeader;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblHouseZipCode;
    private javax.swing.JPanel splitPane;
    private javax.swing.JTable tblHospitalDetails;
    private javax.swing.JTable tblHouseDetails;
    private javax.swing.JTextField txtHospitalAddress;
    private javax.swing.JTextField txtHospitalCity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalZipCode;
    private javax.swing.JTextField txtHouseAddress;
    private javax.swing.JTextField txtHouseCity;
    private javax.swing.JTextField txtHouseName;
    private javax.swing.JTextField txtHouseZipCode;
    // End of variables declaration//GEN-END:variables
}
