package ui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTable;
import model.Hospital;
import model.HospitalDirectory;
import javax.swing.table.DefaultTableModel;
import model.DoctorDirectory;


/**
 *
 * @author Shashank
 */
public class CRUDHospital extends javax.swing.JFrame {

    Hospital hospital;
    HospitalDirectory directory;
    DoctorDirectory directory1;

    // default constructor
    public CRUDHospital() {             
    }
    
    // parameterized constructor passing Hospital directory and doctor directory as a parameter
    public CRUDHospital(HospitalDirectory directory, DoctorDirectory directory1) {
        initComponents();

        this.directory = directory;
        this.directory1 = directory1;
        
        this.setTitle("HOSPITAL MANAGEMENT SYSTEM");   // sets title of the this
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   //exit out of application
        this.setSize(1300, 680);   //sets x and y dimeensions of this
        this.getContentPane().setBackground(Color.darkGray);   //change color of background
        this.setVisible(true); // makes this visible
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblHospitalAdminPage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAddNewHospital = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        lblHospitalAddress = new javax.swing.JLabel();
        txtHospitalAddress = new javax.swing.JTextField();
        lblHospitalCity = new javax.swing.JLabel();
        txtHospitalCity = new javax.swing.JTextField();
        lblHospitalZipCode = new javax.swing.JLabel();
        txtHospitalZipCode = new javax.swing.JTextField();
        lblHospitalPhone = new javax.swing.JLabel();
        txtHospitalPhone = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtHospitalName = new javax.swing.JTextField();
        lblHospitalDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitalDetails = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        lblHospitalEmail = new javax.swing.JLabel();
        txtHospitalEmail = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        BtnHome.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnHome.setText("Home");
        BtnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeMouseClicked(evt);
            }
        });
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        btnHospital.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnHospital.setText("Hospital ");
        btnHospital.setMaximumSize(new java.awt.Dimension(49, 26));
        btnHospital.setMinimumSize(new java.awt.Dimension(49, 26));
        btnHospital.setPreferredSize(new java.awt.Dimension(49, 26));
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });

        btnDoctor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setMaximumSize(new java.awt.Dimension(49, 26));
        btnDoctor.setMinimumSize(new java.awt.Dimension(49, 26));
        btnDoctor.setPreferredSize(new java.awt.Dimension(49, 26));
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(BtnHome)
                .addGap(47, 47, 47)
                .addComponent(btnHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        lblHospitalAdminPage.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblHospitalAdminPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalAdminPage.setText("HOSPITAL PAGE");

        lblAddNewHospital.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblAddNewHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddNewHospital.setText("Add New Hospital");

        lblHospitalName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalName.setText("Hospital Name");
        lblHospitalName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalAddress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalAddress.setText("Address");
        lblHospitalAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalCity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalCity.setText("City");
        lblHospitalCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalZipCode.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalZipCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalZipCode.setText("Zip Code");
        lblHospitalZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHospitalPhone.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalPhone.setText("Phone");
        lblHospitalPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSave.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHospitalDetails.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalDetails.setText("Hospital Details");

        tblHospitalDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblHospitalDetails.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblHospitalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "City", "Zip Code", "Phone", "Email"
            }
        ));
        tblHospitalDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHospitalDetails);

        btnUpdate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCreateDoctor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCreateDoctor.setText("Create Doctor");
        btnCreateDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        lblHospitalEmail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblHospitalEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalEmail.setText("Email");
        lblHospitalEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtHospitalEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalEmailActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHospitalAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jSeparator1)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblAddNewHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257)
                .addComponent(lblHospitalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHospitalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHospitalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(btnCreateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospitalAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddNewHospital)
                    .addComponent(lblHospitalDetails))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHospitalName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHospitalAddress)
                            .addComponent(lblHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHospitalCity)
                            .addComponent(lblHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHospitalZipCode)
                            .addComponent(lblHospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHospitalPhone)
                            .addComponent(lblHospitalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHospitalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHospitalEmail))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnView)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateDoctor)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addGap(319, 319, 319))
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout splitPaneLayout = new javax.swing.GroupLayout(splitPane);
        splitPane.setLayout(splitPaneLayout);
        splitPaneLayout.setHorizontalGroup(
            splitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        splitPaneLayout.setVerticalGroup(
            splitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
//         SAVE button action performed code here:        
        hospital = directory.addNewHospital();

        hospital.setHospitalName(txtHospitalName.getText());
        hospital.setAddress(txtHospitalAddress.getText());
        hospital.setCity(txtHospitalCity.getText());
        hospital.setZipCode(txtHospitalZipCode.getText());
        hospital.setPhone(txtHospitalPhone.getText());
        hospital.setEmail(txtHospitalEmail.getText());

        populateTable();

        //clear text for new entries
        txtHospitalName.setText("");
        txtHospitalAddress.setText("");
        txtHospitalCity.setText("");
        txtHospitalZipCode.setText("");
        txtHospitalPhone.setText("");
        txtHospitalEmail.setText("");
        JOptionPane.showMessageDialog(this, "Hospital details successfully added to the hospital directory");
    }//GEN-LAST:event_btnSaveActionPerformed


    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // UPDATE functionality code here:
        // once data is set on textfield apply update operation
        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        
        // Get table model
        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
        Hospital selectedHospital = (Hospital) tblModel.getValueAt(selectedRowIndex, 0);
        // set data from text field to the selected hospital respective place
        selectedHospital.setHospitalName(txtHospitalName.getText());
        selectedHospital.setAddress(txtHospitalAddress.getText());
        selectedHospital.setCity(txtHospitalCity.getText());
        selectedHospital.setZipCode(txtHospitalZipCode.getText());
        selectedHospital.setPhone(txtHospitalPhone.getText());
        selectedHospital.setEmail(txtHospitalEmail.getText());
        
        tblModel.setValueAt(selectedHospital.getHospitalName(), selectedRowIndex, 0);
        tblModel.setValueAt(selectedHospital.getAddress(), selectedRowIndex, 1);
        tblModel.setValueAt(selectedHospital.getCity(), selectedRowIndex, 2);
        tblModel.setValueAt(selectedHospital.getZipCode(), selectedRowIndex, 3);
        tblModel.setValueAt(selectedHospital.getPhone(), selectedRowIndex, 4);
        tblModel.setValueAt(selectedHospital.getEmail(), selectedRowIndex, 5);
        
        JOptionPane.showMessageDialog(this, "Hospital details updated successfully in the hospital directory");
                
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // DELETE functionality code here:
        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        // invoke the table model
        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
        Hospital selectedHospital = (Hospital) tblModel.getValueAt(selectedRowIndex, 0);
        directory.deleteHospital(selectedHospital);
        JOptionPane.showMessageDialog(this, "Hospital data successfully deleted from the hospital directory");
            
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void populateTable() {
        //invoke the table model
        DefaultTableModel tblmodel = (DefaultTableModel) tblHospitalDetails.getModel();
        tblmodel.setRowCount(0);

        for (Hospital hospital : directory.getDirectory()) {
            

            Object[] row = new Object[6];
            row[0] = hospital;
            row[1] = hospital.getAddress();
            row[2] = hospital.getCity();
            row[3] = hospital.getZipCode();
            row[4] = hospital.getPhone();
            row[5] = hospital.getEmail();

            tblmodel.addRow(row);
        }
    }

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // CREATE doctor directing to next page here:
        CreateDoctor obj = new CreateDoctor(directory1);
        obj.setVisible(true);
        //dispose();
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void txtHospitalEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalEmailActionPerformed

    private void tblHospitalDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalDetailsMouseClicked
        // Hospital details table mouse click event code here:
        // when row is selected, data will set to textfield for update
        //populateDetails(tblHospitalDetails);

//        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
//        // invoke the table model
//        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
//        // get value from respective fields and set it to String Attributes
//
//        txtHospitalName.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
//        txtHospitalAddress.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
//        txtHospitalCity.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
//        txtHospitalZipCode.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
//        txtHospitalPhone.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
//        txtHospitalEmail.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());

    }//GEN-LAST:event_tblHospitalDetailsMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // UPDATE mouse click event code here:
        // when row is selected, data will set tinto textfield for update
//        int selectedRowIndex = tblHospitalDetails.getSelectedRow();
//
//        DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
//        // 
//        txtHospitalName.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
//        txtHospitalAddress.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
//        txtHospitalCity.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
//        txtHospitalZipCode.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
//        txtHospitalPhone.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
//        txtHospitalEmail.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // CANCEL or CLEAR button code here:
        // call function to clear input fields
        clearfields();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // VIEW button code here:
        populateDetails(tblHospitalDetails);
 
    }//GEN-LAST:event_btnViewActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // HOME button action performed code here:
        MainJFrame obj = new MainJFrame();
        obj.setVisible(true);
        //dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseClicked
        // HOME button mouse clicked code here:
        MainJFrame obj = new MainJFrame();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_BtnHomeMouseClicked

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CRUDHospital().setVisible(true);
        });
    }

    private void clearfields() {
        txtHospitalName.setText("");
        txtHospitalAddress.setText("");
        txtHospitalCity.setText("");
        txtHospitalZipCode.setText("");
        txtHospitalPhone.setText("");
        txtHospitalEmail.setText("");

    }

    private void viewHospitalDetails(JTable tblHospitalDetails) {
        int selectedRowIndex = tblHospitalDetails.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            
        } else {
                if (selectedRowIndex == 1) {
                DefaultTableModel tblModel = (DefaultTableModel) tblHospitalDetails.getModel();
                Hospital selectedHospital = (Hospital) tblModel.getValueAt(selectedRowIndex, 0);

                txtHospitalName.setText(selectedHospital.getHospitalName());
                txtHospitalAddress.setText(selectedHospital.getAddress());
                txtHospitalCity.setText(selectedHospital.getCity());
                txtHospitalZipCode.setText(selectedHospital.getZipCode());
                txtHospitalPhone.setText(selectedHospital.getPhone());
                txtHospitalEmail.setText(selectedHospital.getEmail());

            }
        }
}     

        

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAddNewHospital;
    private javax.swing.JLabel lblHospitalAddress;
    private javax.swing.JLabel lblHospitalAdminPage;
    private javax.swing.JLabel lblHospitalCity;
    private javax.swing.JLabel lblHospitalDetails;
    private javax.swing.JLabel lblHospitalEmail;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalPhone;
    private javax.swing.JLabel lblHospitalZipCode;
    private javax.swing.JPanel splitPane;
    private javax.swing.JTable tblHospitalDetails;
    private javax.swing.JTextField txtHospitalAddress;
    private javax.swing.JTextField txtHospitalCity;
    private javax.swing.JTextField txtHospitalEmail;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalPhone;
    private javax.swing.JTextField txtHospitalZipCode;
    // End of variables declaration//GEN-END:variables

   
    private void populateDetails(JTable tblHospitalDetails) {
        int selectedRowIndex = tblHospitalDetails.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel tblmodel = (DefaultTableModel) tblHospitalDetails.getModel();
        Hospital selectedHospital = (Hospital) tblmodel.getValueAt(selectedRowIndex, 0);

        txtHospitalName.setText(selectedHospital.getHospitalName());
        txtHospitalAddress.setText(selectedHospital.getAddress());
        txtHospitalCity.setText(selectedHospital.getCity());
        txtHospitalZipCode.setText(selectedHospital.getZipCode());
        txtHospitalPhone.setText(selectedHospital.getPhone());
        txtHospitalEmail.setText(selectedHospital.getEmail());
       
    }
    
    
}
